import React, {useEffect,useMemo,useState} from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const fallbackStories=[{id:'welcome',slug:'welcome-to-celeb-rumour-wire',title:'Welcome to Celeb Rumour Wire',celeb:'Site News',angle:'Breaking Rumours',summary:'The retro gossip wire is live. Add RSS sources and analytics to make it grow.',rumourWriteup:'Rumour Wire write-up: This is your fallback story while live feeds load.',source:'Celeb Rumour Wire',sourceUrl:'#',publishedAt:new Date().toISOString(),confidence:'Official'}];
function decodeHtml(text){const textarea=document.createElement('textarea');textarea.innerHTML=text||'';return textarea.value;}
function slugify(s){return (s||'story').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)}
function StoryCard({story}){return <a className="card" href={`#/story/${story.slug||story.id}`}><div className="tag">{decodeHtml(story.angle)} · {story.confidence}</div><h2>{decodeHtml(story.title)}</h2><div className="meta">{decodeHtml(story.celeb)} · {story.source} · {new Date(story.publishedAt).toLocaleDateString()}</div><p>{decodeHtml(story.summary)}</p><span className="readmore">READ MORE &gt;&gt;</span></a>}
function Home({stories}){const groups=[['🔥 Breaking Rumours',stories.slice(0,6)],['⭐ Trending Celebs',stories.filter(s=>s.celeb!=='Celebrity News').slice(0,6)],['💔 Breakups',stories.filter(s=>s.angle==='Breakups').slice(0,6)],['📺 Reality TV Drama',stories.filter(s=>s.angle==='Reality TV').slice(0,6)],['🎵 Music Gossip',stories.filter(s=>s.angle==='Music').slice(0,6)]];return <><section className="hero"><div><h1>CELEB RUMOUR WIRE</h1><p>Your chaotic early-2000s celebrity gossip dashboard. Source-led summaries, trending drama and click-through articles.</p></div><div className="blink">LIVE FEED</div></section><div className="ticker"><marquee>BREAKING RUMOURS • CELEB DRAMA • REALITY TV • POP GIRLIES • RED CARPET CHAOS •</marquee></div>{groups.map(([name,list])=>list.length?<section className="section" key={name}><h3>{name}</h3><div className="grid">{list.map(s=><StoryCard key={s.id} story={s}/>)}</div></section>:null)}<Newsletter/></>}
function StoryPage({stories,slug}){const story=stories.find(s=>(s.slug||s.id)===slug)||stories[0]; const related=stories.filter(s=>s.id!==story.id && (s.celeb===story.celeb||s.angle===story.angle)).slice(0,3); useEffect(()=>{document.title=`${decodeHtml(story.title)} | Celeb Rumour Wire`},[story]);return <main className="article"><a href="#/">&lt;&lt; back to front page</a><h1>{decodeHtml(story.title)}</h1><div className="meta big">{decodeHtml(story.celeb)} · {decodeHtml(story.angle)} · {story.source}</div><p className="lede">{decodeHtml(story.summary)}</p><div className="writeup"><b>Rumour Wire take:</b> {decodeHtml(story.rumourWriteup)}</div><p>This page is a short source-led summary for entertainment purposes. For the full original report, use the source link below.</p><p><a className="sourcebtn" href={story.sourceUrl} target="_blank" rel="noreferrer">Open original source</a></p><h3>Related gossip</h3><div className="grid">{related.map(s=><StoryCard key={s.id} story={s}/>)}</div></main>}
function TopicPage({stories,topic}){const pretty=topic.replace(/-/g,' '); const list=stories.filter(s=>slugify(s.angle).includes(topic)||slugify(s.topic).includes(topic)||slugify(s.celeb).includes(topic)); return <><a href="#/">&lt;&lt; home</a><section className="section"><h1>{pretty.toUpperCase()}</h1><div className="grid">{(list.length?list:stories).map(s=><StoryCard key={s.id} story={s}/>)}</div></section></>}
function Newsletter(){return <section className="newsletter"><h3>📬 Daily Gossip Blast</h3><p>Newsletter signup placeholder. Add Mailchimp/Beehiiv later.</p><input placeholder="your@email.com"/><button>JOIN</button></section>}
function App(){const [stories,setStories]=useState(fallbackStories);const [loading,setLoading]=useState(true); const [route,setRoute]=useState(location.hash||'#/'); useEffect(()=>{const f=()=>setRoute(location.hash||'#/');addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]); useEffect(()=>{fetch('/api/stories').then(r=>r.json()).then(d=>{if(d.stories?.length)setStories(d.stories)}).catch(()=>{}).finally(()=>setLoading(false));},[]); const path=route.replace(/^#/,''); let page=<Home stories={stories}/>; if(path.startsWith('/story/')) page=<StoryPage stories={stories} slug={path.split('/story/')[1]}/>; if(path.startsWith('/topic/')) page=<TopicPage stories={stories} topic={path.split('/topic/')[1]}/>; return <div><header><a href="#/" className="logo">★ CELEB RUMOUR WIRE ★</a><nav><a href="#/topic/breakups">Breakups</a><a href="#/topic/reality-tv">Reality TV</a><a href="#/topic/music">Music</a><a href="/privacy.html">Privacy</a></nav></header><div className="layout"><aside><h3>OMG LINKS</h3><a href="#/">Home</a><a href="#/topic/celebrity-rumours">Rumours</a><a href="#/topic/hollywood">Hollywood</a><div className="ad">AD SPACE<br/>728x90 vibes</div></aside><main>{loading?<p>Loading live gossip...</p>:page}</main></div><footer>© Celeb Rumour Wire · Source-led summaries · Retro chaos forever</footer></div>}
createRoot(document.getElementById('root')).render(<App/>);
